### ISSUE TITLE
Error while computing median gradient

### ISSUE THREAD

**Issue by dave07747** [rohitrango/automatic-watermark-detection#1]
Hi there,

I was just checking out your repo and got it started up. However, I ran into an issue computing the median gradient. The error I receive is:

`Traceback (most recent call last):
  File "main.py", line 3, in <module>
    gx, gy, gxlist, gylist = estimate_watermark('portraits')
  File "/mnt/c/Programming/watermark-remover/automatic-watermark-detection-master/src/estimate_watermark.py", line 39, in estimate_watermark
    print(np.median(np.array(gradx), axis=0))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 4097, in median
    overwrite_input=overwrite_input)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 4011, in _ureduce
    r = func(a, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 4155, in _median
    return mean(part[indexer], axis=axis, out=out)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2909, in mean
    out=out, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 57, in _mean
    rcount = _count_reduce_items(arr, axis)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 49, in _count_reduce_items
    for ax in axis:
ValueError: operands could not be broadcast together with shapes (412,321,3) (407,318,3)`

Would you happen to know what's going wrong here?

Thank you!

**Comment by rohitrango** [comment]
Hi, 
It seems like the images you are using do not have the same size. The same was for my dataset (in fact for mostly any dataset). There are a couple of ways around it:
1. Resize all images (not useful) - This is because watermark change size and shape as well.
2. Pad all the image boundaries with zeros - This comes in handy because median image won't be distorted, and as a postprocessing step you can crop the unwatermarked image.

The file `preprocess.py` will most likely be able to help you. Change the `size` parameter to the largest image dimension to preprocess the image set.

**Comment by dave07747** [comment]
Ahhh that makes sense, thank you so much! I'll try it out tomorrow :)

**Comment by rohitrango** [comment]
@dave07747 Please do close the issue if it's resolved. Thanks
